### ISSUE TITLE
某些章节文章是空的就会爬取失败，替换爬取也失败的处理

### ISSUE THREAD

**Issue by DreamCatcherJ** [IceInTheFire/timotaoshu#4]
某些章节文章是空的就会爬取失败，替换爬取也失败的时候，为什么不让删除这些章节？这样子这部书也发布不出去了

**Comment by IceInTheFire** [comment]
某些章节，来源渠道是空的，所以也会爬取失败。
替换爬取是针对特殊章节的，特殊章节爬取失败，就会默认加上“提莫淘书”来填充内容。

不让删除的原因之一：是我们还有连载功能，如果我们的章节少了一个，就会导致连载的时候也少了一个。然后章节就会错乱重复了。
不让删除的原因之二：不让删除的话，就代表它是不可缺少的章节，提醒我们手动填充章节内容，然后填充完了后，我们程序会自动删除错误章节，然后就可以发布了

**Comment by DreamCatcherJ** [comment]
请问替换爬取失败在哪里手动填充章节内容？

**Comment by IceInTheFire** [comment]
爬取错误列表，直接点进去，进入章节内容页面，然后，手动去其他网站复制内容，最后粘贴到章节内容里。
方法很low的
